version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: temporal-postgres
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
      POSTGRES_DB: temporal
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  temporal:
    image: temporalio/auto-setup:1.25
    container_name: temporal
    depends_on:
      - postgres
    ports:
      - "7233:7233"
    environment:
      - DB=postgres12
      # Temporal DB connection settings
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgres

  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: temporal-ui
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  parser-service:
    build:
      context: .
      dockerfile: ./parser-service/Dockerfile
    container_name: parser-service
    depends_on:
      - temporal
    environment:
      - TEMPORAL_HOST=temporal:7233
    volumes:
      - documents:/documents

  parser-service-ui:
    build:
      context: .
      dockerfile: ./parser-service/Dockerfile
    container_name: parser-service-ui
    depends_on:
      - parser-service
    command: >
      streamlit run streamlit_app/app.py
      --server.port=8501
      --server.address=0.0.0.0
    ports:
      - "8501:8501"

  generator-service:
    build:
      context: .
      dockerfile: ./generator-service/Dockerfile
    container_name: generator-service
    depends_on:
      - temporal
      - redis
    environment:
      - TEMPORAL_HOST=temporal:7233
      - REDIS_URL=redis://redis:6379
    volumes:
      - documents:/documents

  workflow-orchestrator:
    build:
      context: .
      dockerfile: ./workflow-orchestrator/Dockerfile
    container_name: workflow-orchestrator
    depends_on:
      - temporal
    environment:
      - TEMPORAL_HOST=temporal:7233

  api-service:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    container_name: api-service
    ports:
      - "8000:8000"
    depends_on:
      - temporal
      - workflow-orchestrator
      - redis
    environment:
      - TEMPORAL_HOST=temporal:7233
      - REDIS_URL=redis://redis:6379
    volumes:
      - documents:/documents

volumes:
  documents:
